contact_links:
  - name: "üõ°Ô∏è Reporting security issues"
    url: https://github.com/4TUResearchData/djehuty?tab=readme-ov-file#reporting-potential-security-issues
    about: ‚ö†Ô∏è IMPORTANT - For security-related matters, DO NOT create an issue. Please e-mail djehuty@4tu.nl.
  - name: "üì£ Contact information"
    url: https://github.com/4TUResearchData/djehuty/blob/main/GOVERNANCE.md#contact-information
    about: Get in touch with us.
  - name: "‚≠ê Join the 4TU ResearchData community"
    url: https://community.data.4tu.nl/
    about: The 4TU.ResearchData community is built around an international data repository for science, engineering and design. Connect with members and exchange knowledge about best practices for the creation and reuse of FAIR data.